server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location = /configuratori-3d.html {
        return 301 http://$http_host/digital-experience.html;
    }

    location ~ /\. {
        deny all;
        return 404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ ^/api/contact\.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/api/contact.php;
        fastcgi_param HTTP_X_REAL_IP $remote_addr;
        fastcgi_pass php:9000;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
